[env]
  TERM = "xterm-256color"
  WINIT_X11_SCALE_FACTOR = "1"

[window]
  dimensions = { columns = 140, lines = 36 }
  opacity = 0.95
  dynamic_padding = true
  dynamic_title = true
  decorations = "Full"

[font]
  normal = { family = "JetbrainsMonoNL Nerd Font Mono", style = "Medium" }
  bold = { family = "JetbrainsMonoNL Nerd Font Mono", style = "Medium" }
  size = 12

[selection]
  save_to_clipboard = true

[colors.primary]
  background = "#121212"

[keyboard]
  [[keyboard.bindings]]
    key = "W"
    mods = "Control|Shift"
    action = "Quit"

    #[terminal]

    #  [terminal.shell]
    #    program = "/usr/bin/tmux"
    #    args = ["new-session", "-A", "-D", "-s", "Home"]
