gui:
  border: hidden
logs:
  since: ''
  tail: '300'
customCommands:
  containers:
    - name: bash
      attach: true
      command: 'docker exec -it {{ .Container.ID }} bash'
      serviceNames: []
    - name: sh
      attach: true
      command: 'docker exec -it {{ .Container.ID }} sh'
      serviceNames: []
